build(deps): add `base64` as a development dependency
`base64` is no longer part of the standard `Ruby` library.

Error:
```
LoadError: cannot load such file -- base64 (LoadError)
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop/formatter/html_formatter.rb:6:in '<top (required)>'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop.rb:589:in 'Kernel#require_relative'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop.rb:589:in '<top (required)>'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop/rake_task.rb:40:in 'RuboCop::RakeTask#run_cli'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop/rake_task.rb:28:in 'block (2 levels) in RuboCop::RakeTask#initialize'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rubocop-0.80.1/lib/rubocop/rake_task.rb:26:in 'block in RuboCop::RakeTask#initialize'
/home/runner/work/cose-ruby/cose-ruby/vendor/bundle/ruby/3.4.0/gems/rake-13.2.1/exe/rake:27:in '<top (required)>'
/opt/hostedtoolcache/Ruby/3.4.2/x64/bin/bundle:25:in 'Kernel#load'
/opt/hostedtoolcache/Ruby/3.4.2/x64/bin/bundle:25:in '<main>'
Tasks: TOP => default => rubocop
(See full trace by running task with --trace)
```